# Generated by Django 4.2.5 on 2023-09-10 13:40

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProjectOne",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slack_name", models.CharField(blank=True, max_length=50, null=True)),
                ("current_day", models.DateField(blank=True, null=True)),
                ("track", models.CharField(blank=True, max_length=250, null=True)),
                ("utc_time", models.DateTimeField(blank=True, null=True)),
                (
                    "github_file_url",
                    models.URLField(blank=True, max_length=300, null=True),
                ),
                ("github_repo_url", models.URLField(blank=True, null=True)),
                ("status_code", models.IntegerField(blank=True, null=200)),
            ],
        ),
    ]
